    version: '2'
    services:
       microservice:
        image: 'proof-of-concept:latest'
        expose:
          - '8888'
       loadbalancer:
        image: 'dockercloud/haproxy:latest'
        links:
          - microservice
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - '80:80'